CXX = g++

g++ HttpRequestTest.cc ../HttpRequest.cc ../../utils/utils.cc ../../buffer/Buffer.cc -o HttpRequestTest -std=c++11

g++ HttpResponseTest.cc ../HttpResponse.cc ../HttpRequest.cc ../HttpConn.cc ../../buffer/Buffer.cc -o HttpResponseTest -std=c++11

g++ HttpConnTest.cc ../HttpResponse.cc ../HttpRequest.cc ../HttpConn.cc ../../buffer/Buffer.cc -o HttpConnTest -std=c++11