CXX = g++

g++ HttpRequestTest.cc ../HttpRequest.cc ../../utils/utils.cc ../../buffer/Buffer.cc -o HttpRequestTest -std=c++11

g++ HttpResponseTest.cc ../../socket/InetAddr.cc -o HttpResponseTest -std=c++11